#
#--Makefile to call the commands in src/Makefile
#
make:
	cd src; make eta; make sph; make one; make disc

eta:
	cd src; make eta

sph:
	cd src; make sph

one:
	cd src; make one

disc:
	cd src; make disc

clean:
	cd src; make clean

allclean:
	cd src; make allclean

texclean:
	cd Modifications_src/Figures; rm *pdf; cd ..; mv modifications.pdf ..
